# Generated by Django 6.1.1 on 2026-10-03 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('professor', models.CharField(blank=True, max_length=100)),
                ('color_code', models.CharField(default='#3B82F6', help_text='culoare hex pentru UI', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('next_step', models.TextField(blank=True, help_text='Urmatorul pas concret de facut la proiect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='DebugLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ex:Segfault in alocatorul de memorie', max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('solution', models.TextField(help_text='Cum am rezolvat eroarea / explicatia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_logs', to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, help_text='ce mai trebuie adaugat / detalii')),
                ('priority', models.CharField(choices=[('LOW', 'Scăzută'), ('MEDIUM', 'Medie'), ('HIGH', 'Ridicată')], default='MEDIUM', max_length=10)),
                ('estimated_hours', models.FloatField(default=1.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academic.project')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TestPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ex: Test Laborator 1', max_length=200)),
                ('test_date', models.DateTimeField()),
                ('topics_to_cover', models.TextField(help_text='Lista de concepte / capitole de invatat')),
                ('solved_questions', models.TextField(blank=True, help_text='Intrebari frecvente si rezolvari')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_preps', to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='WeekendPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ex: Plan weekend 4-5 Octombrie', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('tasks', models.ManyToManyField(blank=True, related_name='weekend_plans', to='academic.task')),
            ],
        ),
    ]
