# Generated by Django 6.1.1 on 2026-10-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, help_text='Link GitHub/GitLab/Drive'),
        ),
    ]
