# Generated by Django 6.1.1 on 2026-10-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_project_repository_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_work',
            field=models.TextField(blank=True, help_text='Ce am realizat până acum'),
        ),
        migrations.AddField(
            model_name='project',
            name='pending_work',
            field=models.TextField(blank=True, help_text='Ce mai trebuie adăugat / de făcut'),
        ),
    ]
