# Generated by Django 6.1.1 on 2026-10-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_project_completed_work_project_pending_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex:Examen Final, Proiect PM, Test Lab 1', max_length=100)),
                ('weight_percentage', models.FloatField(help_text='Pondere in Nota Finala(ex:40%)')),
                ('obtained_grade', models.FloatField(blank=True, help_text='Nota obtinuta', null=True)),
                ('is_exam', models.BooleanField(default=False, help_text='Marcheaza daca aceasta este componenta de Examen ')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_components', to='academic.subject')),
            ],
        ),
    ]
