# Generated by Django 6.1.1 on 2026-10-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_gradecomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradecomponent',
            name='is_exam',
        ),
        migrations.RemoveField(
            model_name='gradecomponent',
            name='weight_percentage',
        ),
        migrations.AddField(
            model_name='gradecomponent',
            name='category',
            field=models.CharField(choices=[('ACTIVITY', 'Activitate / Laborator / Proiect'), ('EXAM', 'Examen Final')], default='ACTIVITY', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='grading_formula',
            field=models.CharField(choices=[('50_50', 'Medie Aritmetică (50% Activitate / 50% Examen)'), ('33_66', '33% Activitate / 66% Examen'), ('40_60', '40% Activitate / 60% Examen'), ('30_70', '30% Activitate / 70% Examen')], default='50_50', help_text='Modul de combinare între Nota de Activitate și Nota de Examen', max_length=10),
        ),
    ]
