# Generated by Django 6.1.1 on 2026-10-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_gradecomponent_is_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=25, help_text='Durata sesiunii în minute')),
                ('session_type', models.CharField(choices=[('POMODORO', 'Sesiune Pomodoro'), ('MANUAL', 'Introducere Manuală')], default='POMODORO', max_length=20)),
                ('notes', models.CharField(blank=True, help_text='La ce ai lucrat în această sesiune (opțional)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='academic.subject')),
            ],
        ),
    ]
