# Generated by Django 6.1.1 on 2026-10-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_studysession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Întrebarea sau conceptul de verificat')),
                ('answer', models.TextField(help_text='Răspunsul sau explicația corectă')),
                ('is_mastered', models.BooleanField(default=False, help_text='Marchează dacă ai învățat deja acest card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='academic.subject')),
            ],
        ),
    ]
